// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbif_K_o4cmBHbsKzuZkV_P9yNJa1BFK0',
    appId: '1:943777440657:web:f9fa201ce10e0fd9b6f030',
    messagingSenderId: '943777440657',
    projectId: 'finance4people-58004',
    authDomain: 'finance4people-58004.firebaseapp.com',
    storageBucket: 'finance4people-58004.appspot.com',
    measurementId: 'G-VM2K6W10KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDh_5hTUFm50ggUhbGVu7zTr1C8Tf4Rlc',
    appId: '1:943777440657:android:4c87653fa0b5ef9bb6f030',
    messagingSenderId: '943777440657',
    projectId: 'finance4people-58004',
    storageBucket: 'finance4people-58004.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjS4fQmFQzUkcTQjKZVxXtjJ9HwrUCbnI',
    appId: '1:943777440657:ios:ba5bba36826a5d1eb6f030',
    messagingSenderId: '943777440657',
    projectId: 'finance4people-58004',
    storageBucket: 'finance4people-58004.appspot.com',
    iosClientId: '943777440657-vkvb1f96v75td81bg4ilu083kqodhrpo.apps.googleusercontent.com',
    iosBundleId: 'com.gabor.finance4people',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjS4fQmFQzUkcTQjKZVxXtjJ9HwrUCbnI',
    appId: '1:943777440657:ios:ba5bba36826a5d1eb6f030',
    messagingSenderId: '943777440657',
    projectId: 'finance4people-58004',
    storageBucket: 'finance4people-58004.appspot.com',
    iosClientId: '943777440657-vkvb1f96v75td81bg4ilu083kqodhrpo.apps.googleusercontent.com',
    iosBundleId: 'com.gabor.finance4people',
  );
}
